#!/usr/bin/env python3
"""Generate `airplay_play_kat.json` from pyatv itself.

pyatv has no factory for the `play_url` bodies — `AirPlayV1.play_url` and `AirPlayV2.play_url`
build their dictionaries inline (`pyatv/protocols/raop/protocols/airplayv1.py:126-130`,
`airplayv2.py:213-236`, `airplayv2.py:57-72`), so there is nothing importable to call. What this
script does instead is *read those dictionaries out of the running module's own source* with `ast`,
substitute the handful of per-call values (the URL, the position, the UUIDs, the timing port) and
hand the result to `plistlib`. That keeps the vector honest in the way that matters: the key set,
the key order and every literal come from the checkout rather than from this file, so a value pyatv
changes shows up as a regenerated vector rather than as a silently stale constant.

The comparison on the Rust side is **after decoding**. `plistlib` and the Rust `plist` crate both
emit valid `bplist00` but make different, equally legal choices about the offset table, so
requiring equal bytes would be stricter than the format is — the same reasoning
`gen_airplay_tunnel_kat.py` records.

Regenerate with:

    PYTHONPATH=/path/to/pyatv python3 gen_airplay_play_kat.py > airplay_play_kat.json

Recorded against pyatv b277a4c (release 0.18.0).
"""

import ast
import inspect
import json
import plistlib

from pyatv.protocols.raop.protocols import airplayv1, airplayv2

# Pinned per-call values, so the vector is reproducible. In a real session every one of these is
# freshly drawn or supplied by the caller.
URL = "http://airplaystream/video.mp4"
POSITION = 0.8
V1_SESSION_ID = "1a2b3c4d-5e6f-4a8b-9c0d-1e2f3a4b5c6d"
V2_UUID = "2b3c4d5e-6f7a-4b8c-9d0e-2f3a4b5c6d7e"
SETUP_SESSION_UUID = "3C4D5E6F-7A8B-4C9D-8E0F-3A4B5C6D7E8F"
TIMING_PORT = 6002

# What the placeholder expressions in those source dictionaries evaluate to here.
SUBSTITUTIONS = {
    "url": URL,
    "position": POSITION,
    "str(uuid4())": V1_SESSION_ID,
    "self.uuid": V2_UUID,
    "str(uuid4()).upper()": SETUP_SESSION_UUID,
    "timing_server_port": TIMING_PORT,
}


def _literal(node):
    """Evaluate one dictionary value, using `SUBSTITUTIONS` for anything not a literal."""
    source = ast.unparse(node)
    if source in SUBSTITUTIONS:
        return SUBSTITUTIONS[source]
    return ast.literal_eval(node)


def _dict_from(function, marker):
    """Pull the first dict literal that follows `marker` out of `function`'s source."""
    tree = ast.parse(inspect.getsource(function).lstrip())
    for node in ast.walk(tree):
        if not isinstance(node, ast.Dict):
            continue
        keys = [key.value for key in node.keys if isinstance(key, ast.Constant)]
        if marker not in keys:
            continue
        return {
            key.value: _literal(value)
            for key, value in zip(node.keys, node.values)
        }
    raise SystemExit(f"no dictionary containing {marker!r} in {function.__qualname__}")


def _headers(module):
    """The module-level `HEADERS` dict, with the per-process session id pinned.

    Emitted as a list of pairs rather than an object: header order is part of what goes on the
    wire, and a JSON object gives the reader no promise about it.
    """
    return [
        [name, V2_UUID if name == "X-Apple-Session-ID" else value]
        for name, value in module.HEADERS.items()
    ]


def main():
    v1_play = _dict_from(airplayv1.AirPlayV1.play_url, "Content-Location")
    v1_play["X-Apple-Session-ID"] = V1_SESSION_ID

    v2_play = _dict_from(airplayv2.AirPlayV2.play_url, "Content-Location")
    v2_setup = _dict_from(airplayv2.AirPlayV2._setup_base, "timingProtocol")

    end_time = {"flags": 0, "value": 0, "epoch": 0, "timescale": 0}

    print(
        json.dumps(
            {
                "_comment": (
                    "Known-answer vectors for AirPlay `play_url`, generated by "
                    "tests/kat/gen_airplay_play_kat.py against pyatv b277a4c. `plists` are "
                    "lowercase hex of bplist00 documents compared after decoding, since "
                    "offset-table choices differ legally between plistlib and the Rust plist "
                    "crate. Do not edit by hand: regenerate."
                ),
                "_source": {
                    "pyatv": (
                        "pyatv/protocols/raop/protocols/airplayv1.py, "
                        "pyatv/protocols/raop/protocols/airplayv2.py"
                    )
                },
                "session": {
                    "url": URL,
                    "position": POSITION,
                    "v1_session_id": V1_SESSION_ID,
                    "v2_uuid": V2_UUID,
                    "setup_session_uuid": SETUP_SESSION_UUID,
                    "timing_port": TIMING_PORT,
                },
                "headers": {
                    "v1_play": _headers(airplayv1),
                    "v2_play": _headers(airplayv2),
                },
                "keys": {
                    "v1_play": list(v1_play),
                    "v2_play": list(v2_play),
                    "v2_base_setup": list(v2_setup),
                },
                "plists": {
                    "v1_play": plistlib.dumps(v1_play, fmt=plistlib.FMT_BINARY).hex(),
                    "v2_play": plistlib.dumps(v2_play, fmt=plistlib.FMT_BINARY).hex(),
                    "v2_base_setup": plistlib.dumps(
                        v2_setup, fmt=plistlib.FMT_BINARY
                    ).hex(),
                    "set_property_true": plistlib.dumps(
                        {"value": True}, fmt=plistlib.FMT_BINARY
                    ).hex(),
                    "set_property_zero": plistlib.dumps(
                        {"value": 0}, fmt=plistlib.FMT_BINARY
                    ).hex(),
                    "set_property_end_time": plistlib.dumps(
                        {"value": end_time}, fmt=plistlib.FMT_BINARY
                    ).hex(),
                },
            },
            indent=2,
        )
    )


if __name__ == "__main__":
    main()
