#!/usr/bin/env python3
"""Generate `airplay_tunnel_kat.json` from pyatv itself.

The AirPlay 2 remote-control tunnel has **no automated coverage anywhere in pyatv's own test tree**
— grepping it for `eventPort`, `dataPort`, `isRemoteControlOnly`, `DataStreamChannel`,
`EventChannel`, `AP2Session` or `setup_remote_control` returns nothing
(`docs/research/airplay-control-mrp-tunnel-port-spec.md` §16.2). Every claim about these bytes is a
reading of pyatv's source, so the least this port can do is ask pyatv to produce them and pin the
answer.

Three families of vector live in the output file:

* `data_frames` — whole frames from `BaseDataStreamChannel.encode_message`, the real encoder, so the
  32-byte big-endian `DataHeader` layout is checked against the implementation rather than against a
  reading of `defpacket`'s format string. Compared byte for byte.
* `variants` — `pyatv.support.variant.write_variant` outputs, byte for byte.
* `plists` — the two RTSP `SETUP` bodies and the data-channel envelope, from `plistlib` /
  `pyatv.protocols.airplay.utils.encode_plist_body`. Compared **after decoding**: `plistlib` and the
  Rust `plist` crate both emit valid `bplist00` but make different, equally legal choices about the
  offset table, so requiring equal bytes would be stricter than the format is.

The per-session values (`sessionUUID`, `seed`, `channelID`, `clientUUID`, `seqno`) are pinned here
so the vector is reproducible; in a real session they are freshly drawn every time.

Regenerate with:

    PYTHONPATH=/path/to/pyatv python3 gen_airplay_tunnel_kat.py > airplay_tunnel_kat.json

Recorded against pyatv b277a4c (release 0.18.0).
"""

import json
import plistlib

from pyatv.protocols.airplay.channels import (
    DATA_HEADER_PADDING,
    BaseDataStreamChannel,
    DataStreamMessage,
)
from pyatv.protocols.airplay.utils import encode_plist_body
from pyatv.settings import InfoSettings
from pyatv.support.variant import write_variant

# Pinned per-session values. `SEED` is the same one `hap_srp_kat.json` salts the data-stream keys
# with, so the two files describe one coherent session.
SESSION_UUID = "1A2B3C4D-5E6F-4A8B-9C0D-1E2F3A4B5C6D"
CHANNEL_ID = "2B3C4D5E-6F7A-4B8C-9D0E-2F3A4B5C6D7E"
CLIENT_UUID = "3C4D5E6F-7A8B-4C9D-8E0F-3A4B5C6D7E8F"
SEED = 3141592653589793
SEQNO = 0x1234567890

# A stand-in `ProtocolMessage`. The leading 0x08 is field 1 (`type`) with wire type 0, which is what
# `decode_protobufs`' unprefixed-message heuristic keys off (`channels.py:204-212`). Its length is
# deliberately realistic: pyatv's own comment reasons that "the minimal message length is at least
# 40 (type and uniqueIdentifier)", which is exactly what makes a leading 0x08 unambiguous — an
# eight-byte message would encode a length prefix of 0x08 and be indistinguishable from an
# unprefixed one, in pyatv as much as here.
MESSAGE = bytes([0x08, 0x2A, 0x52, 0x24]) + b"1A2B3C4D-5E6F-4A8B-9C0D-1E2F3A4B5C6D"

INFO = InfoSettings()


def event_setup_body():
    """`AP2Session._setup_event_channel`'s dictionary, verbatim (`ap2_session.py:119-133`)."""
    return {
        "isRemoteControlOnly": True,
        "osName": INFO.os_name,
        "sourceVersion": "550.10",
        "timingProtocol": "None",
        "model": INFO.model,
        "deviceID": INFO.device_id,
        "osVersion": INFO.os_version,
        "osBuildVersion": INFO.os_build,
        "macAddress": INFO.mac,
        "sessionUUID": SESSION_UUID,
        "name": INFO.name,
    }


def data_setup_body():
    """`AP2Session._setup_data_channel`'s dictionary, verbatim (`ap2_session.py:158-172`)."""
    return {
        "streams": [
            {
                "controlType": 2,
                "channelID": CHANNEL_ID,
                "seed": SEED,
                "clientUUID": CLIENT_UUID,
                "type": 130,
                "wantsDedicatedSocket": True,
                "clientTypeUUID": "1910A70F-DBC0-4242-AF95-115DB30604E1",
            }
        ]
    }


def sync_frame():
    """What `send_protobuf` puts on the wire for one message (`channels.py:266-280`)."""
    payload = encode_plist_body(
        {"params": {"data": write_variant(len(MESSAGE)) + MESSAGE}}
    )
    return BaseDataStreamChannel.encode_message(
        DataStreamMessage(
            b"sync" + 8 * b"\x00", b"comm", SEQNO, DATA_HEADER_PADDING, payload
        )
    )


def reply_frame():
    """What acknowledges one (`channels.py:153-163`)."""
    return BaseDataStreamChannel.encode_message(
        DataStreamMessage(
            b"rply" + 8 * b"\x00", 4 * b"\x00", SEQNO, DATA_HEADER_PADDING, b""
        )
    )


def main():
    document = {
        "_comment": (
            "Known-answer vectors for the AirPlay 2 remote-control tunnel, generated by "
            "tests/kat/gen_airplay_tunnel_kat.py against pyatv b277a4c. `data_frames` and "
            "`variants` are lowercase hex compared byte for byte; `plists` are lowercase hex of "
            "bplist00 documents compared after decoding, since offset-table choices differ "
            "legally between plistlib and the Rust plist crate. Do not edit by hand: regenerate."
        ),
        "_source": {
            "pyatv": (
                "pyatv/protocols/airplay/ap2_session.py, "
                "pyatv/protocols/airplay/channels.py, "
                "pyatv/support/variant.py"
            )
        },
        "session": {
            "session_uuid": SESSION_UUID,
            "channel_id": CHANNEL_ID,
            "client_uuid": CLIENT_UUID,
            "seed": SEED,
            "seqno": SEQNO,
            "message": MESSAGE.hex(),
        },
        "info_settings": {
            "name": INFO.name,
            "mac": INFO.mac,
            "device_id": INFO.device_id,
            "model": INFO.model,
            "os_name": INFO.os_name,
            "os_build": INFO.os_build,
            "os_version": INFO.os_version,
        },
        "data_frames": {
            "sync": sync_frame().hex(),
            "reply": reply_frame().hex(),
        },
        "variants": {
            str(value): write_variant(value).hex()
            for value in [0, 1, 127, 128, 300, 16383, 16384, len(MESSAGE)]
        },
        "plists": {
            "event_setup_body": plistlib.dumps(
                event_setup_body(), fmt=plistlib.FMT_BINARY
            ).hex(),
            "data_setup_body": plistlib.dumps(
                data_setup_body(), fmt=plistlib.FMT_BINARY
            ).hex(),
            "envelope": encode_plist_body(
                {"params": {"data": write_variant(len(MESSAGE)) + MESSAGE}}
            ).hex(),
        },
    }

    print(json.dumps(document, indent=2, sort_keys=True))


if __name__ == "__main__":
    main()
