//! Loader for `hap_srp_kat.json`, the cross-implementation vectors.
//!
//! The file is generated by `gen_hap_srp_kat.py` in this directory from pyatv and pyatv's own
//! dependencies; see that script's header for how to regenerate it. It is embedded with
//! `include_str!` so the tests never touch the filesystem and a missing file is a compile error
//! rather than a skipped test.
//!
//! Fields are addressed by a `/`-separated path (`"srp/client_proof_m1"`). A missing or
//! wrong-shaped field panics with the path in the message, because a vector that has silently
//! changed shape must fail loudly rather than assert on `None`.

use serde_json::Value;

/// One row of the `transport_keys` table: the salt/info literals a pyatv call site passed, and the
/// two keys they produced.
#[derive(Debug)]
pub struct Channel {
    /// The `channel` key, used only in assertion messages.
    pub name: String,
    /// HKDF salt, already including the data-stream session seed where one applies.
    pub salt: String,
    /// Info string for the key the controller encrypts with.
    pub output_info: String,
    /// Info string for the key the controller decrypts with.
    pub input_info: String,
    /// Expected output key.
    pub output_key: [u8; 32],
    /// Expected input key.
    pub input_key: [u8; 32],
}

/// The parsed vector document.
#[derive(Debug)]
pub struct Kat(Value);

impl Kat {
    /// Parse the embedded vectors.
    #[must_use]
    pub fn load() -> Self {
        Self(
            serde_json::from_str(include_str!("hap_srp_kat.json"))
                .expect("hap_srp_kat.json is not valid JSON; regenerate it"),
        )
    }

    /// The string at `path`.
    #[must_use]
    pub fn text(&self, path: &str) -> &str {
        self.at(path)
            .as_str()
            .unwrap_or_else(|| panic!("{path} is not a string"))
    }

    /// The hex string at `path`, decoded.
    #[must_use]
    pub fn bytes(&self, path: &str) -> Vec<u8> {
        hex::decode(self.text(path)).unwrap_or_else(|_| panic!("{path} is not hex"))
    }

    /// The hex string at `path`, decoded into a fixed-size array.
    #[must_use]
    pub fn array<const N: usize>(&self, path: &str) -> [u8; N] {
        let bytes = self.bytes(path);
        let length = bytes.len();
        bytes
            .try_into()
            .unwrap_or_else(|_| panic!("{path} is {length} bytes, expected {N}"))
    }

    /// The transport-key table at `path`.
    #[must_use]
    pub fn channels(&self, path: &str) -> Vec<Channel> {
        let rows = self
            .at(path)
            .as_array()
            .unwrap_or_else(|| panic!("{path} is not an array"));

        (0..rows.len())
            .map(|index| Channel {
                name: self.text(&format!("{path}/{index}/channel")).to_owned(),
                salt: self.text(&format!("{path}/{index}/salt")).to_owned(),
                output_info: self.text(&format!("{path}/{index}/output_info")).to_owned(),
                input_info: self.text(&format!("{path}/{index}/input_info")).to_owned(),
                output_key: self.array(&format!("{path}/{index}/output_key")),
                input_key: self.array(&format!("{path}/{index}/input_key")),
            })
            .collect()
    }

    /// Walk a `/`-separated path, indexing arrays by decimal position.
    fn at(&self, path: &str) -> &Value {
        path.split('/').fold(&self.0, |value, key| {
            match key.parse::<usize>() {
                Ok(index) => value.get(index),
                Err(_) => value.get(key),
            }
            .unwrap_or_else(|| panic!("{path} is not present in hap_srp_kat.json"))
        })
    }
}
