//! Known-answer vectors generated by pyatv itself.
//!
//! Everything here is checked against bytes `pyatv` produced, not against bytes this port produced
//! and someone eyeballed. `tests/kat/gen_companion_kat.py` regenerates the fixture; its header
//! documents how and against which pyatv revision.
//!
//! Two kinds of comparison, and the difference matters:
//!
//! * **OPACK payloads are compared byte for byte.** OPACK's back-reference table indexes values by
//!   first appearance, so key order is part of the encoding and a "harmlessly tidied" dictionary is
//!   a different payload on the wire. `_hidC` is the sharp case: `"_hidC"` appears as both the
//!   message identifier and a content key, and the second occurrence must come out as the one-byte
//!   pointer `0xA1`.
//! * **The RTI `NSKeyedArchiver` payloads are compared after decoding.** `plistlib` and the Rust
//!   `plist` crate both emit valid binary plists but make different, equally legal choices about
//!   the offset table and integer widths, so requiring equal bytes would be requiring more than the
//!   format does. What has to match is the object graph: the archiver name, the `$top` mapping, and
//!   the numbering of every `$objects` slot, which is what a device actually reads.

use plist::Value as Plist;
use pyatv_opack::{Value, opack};
use pyatv_proto_companion::message::Envelope;
use pyatv_proto_companion::plist_payloads::{rti_clear_text_payload, rti_input_text_payload};
use pyatv_proto_companion::session::SystemInfo;

/// The generated vectors, embedded so a missing file is a compile error rather than a skip.
const KAT: &str = include_str!("kat/companion_kat.json");

/// The `_x` values baked into the fixture, one per vector, in order.
const XIDS: [u32; 6] = [12345, 12346, 12347, 12348, 12349, 12350];

fn vectors(kind: &str) -> Vec<serde_json::Value> {
    let document: serde_json::Value =
        serde_json::from_str(KAT).expect("the fixture must be valid JSON");
    document[kind]
        .as_array()
        .unwrap_or_else(|| panic!("the fixture must have a `{kind}` array"))
        .clone()
}

fn field(vector: &serde_json::Value, key: &str) -> String {
    vector[key]
        .as_str()
        .unwrap_or_else(|| panic!("vector is missing `{key}`: {vector}"))
        .to_owned()
}

fn expected_bytes(vector: &serde_json::Value, key: &str) -> Vec<u8> {
    hex::decode(field(vector, key)).expect("the fixture stores hex")
}

/// Build the wire dict the way [`crate`]'s own send path does: envelope first, `_x` appended last.
///
/// This mirrors `Envelope::to_value` followed by `CompanionProtocol::exchange_opack`'s stamping
/// (`protocol.py:181-183`) without needing a socket.
fn stamped(envelope: &Envelope, xid: u32) -> Value {
    let Value::Dict(mut entries) = envelope.to_value() else {
        panic!("an envelope is a dict");
    };
    entries.push((Value::from("_x"), Value::from(xid)));
    Value::Dict(entries)
}

fn system_info() -> SystemInfo {
    let mut info = SystemInfo::new(b"4D797FD3-3538-427E-A47B-A32FC6CF3A6A".to_vec());
    info.rp_id = Some("aabbccddeeff".to_owned());
    info
}

/// The six request and event payloads, byte for byte against `opack.pack`.
#[test]
fn the_request_payloads_match_pyatv_byte_for_byte() {
    let ours = [
        Envelope::request("_systemInfo", system_info().to_content()),
        Envelope::request("_hidC", opack! { "_hBtS" => 1u64, "_hidC" => 6u64 }),
        Envelope::request("_hidC", opack! { "_hBtS" => 2u64, "_hidC" => 6u64 }),
        Envelope::event(
            "_interest",
            opack! { "_regEvents" => Value::array(["_iMC"]) },
        ),
        Envelope::request(
            "_launchApp",
            opack! { "_bundleID" => "com.netflix.Netflix" },
        ),
        Envelope::request("_launchApp", opack! { "_urlS" => "https://tv.apple.com" }),
    ];

    let vectors = vectors("opack");
    assert_eq!(
        vectors.len(),
        ours.len(),
        "every fixture vector needs a counterpart here"
    );

    for ((vector, envelope), xid) in vectors.iter().zip(&ours).zip(XIDS) {
        let name = field(vector, "name");
        let packed = pyatv_opack::pack(&stamped(envelope, xid)).expect("the payload must pack");

        assert_eq!(
            packed.as_ref(),
            expected_bytes(vector, "packed").as_slice(),
            "{name}: {}",
            field(vector, "note")
        );
    }
}

/// `_hidC` is the vector that proves back-references are emitted where pyatv emits them.
///
/// The identifier `"_hidC"` is interned on its first appearance and the content key that repeats it
/// comes out as the one-byte pointer `0xA1`. A payload that spelled the string out twice would
/// still decode, but it would not be the bytes pyatv sends, and this port's whole claim is that it
/// is indistinguishable on the wire.
#[test]
fn a_repeated_key_is_emitted_as_a_back_reference() {
    let vector = vectors("opack")
        .into_iter()
        .find(|vector| field(vector, "name") == "_hidC down")
        .expect("the fixture has the _hidC vector");

    let packed = expected_bytes(&vector, "packed");
    assert!(
        packed.windows(1).any(|window| window == [0xA1]),
        "pyatv's own encoding interns the repeated identifier"
    );

    // And it round-trips: the pointer resolves back to the string it stands for.
    let (decoded, consumed) = pyatv_opack::unpack(&packed).expect("pyatv's bytes must decode");
    assert_eq!(consumed, packed.len());
    assert_eq!(decoded.get("_i").and_then(Value::as_str), Some("_hidC"));
    assert_eq!(
        decoded
            .get("_c")
            .and_then(|content| content.get("_hidC"))
            .and_then(Value::as_u64),
        Some(6)
    );
}

/// The two RTI archives, compared as decoded object graphs.
#[test]
fn the_rti_payloads_decode_to_pyatvs_object_graphs() {
    for vector in vectors("plist") {
        let name = field(&vector, "name");
        let session_uuid = expected_bytes(&vector, "session_uuid");

        let ours = match vector["text"].as_str() {
            Some(text) => rti_input_text_payload(&session_uuid, text),
            None => rti_clear_text_payload(&session_uuid),
        };

        let theirs = expected_bytes(&vector, "payload");
        assert_eq!(
            parse(&ours),
            parse(&theirs),
            "{name}: {}",
            field(&vector, "note")
        );
    }
}

/// Decoding is what makes the comparison meaningful, so a payload that does not decode at all must
/// fail loudly rather than compare equal to another failure.
fn parse(payload: &[u8]) -> Plist {
    Plist::from_reader(std::io::Cursor::new(payload)).expect("a valid binary plist")
}
