//! The MRP message types, generated from pyatv's `.proto` corpus.
//!
//! `proto/` holds 77 `.proto` files copied verbatim from pyatv (see `proto/README.md` for the
//! source commit and the licence). `build.rs` compiles them with `protox` — a pure-Rust protobuf
//! compiler, so no `protoc` binary and no network access is needed — and generates Rust with
//! `prost-build`. Everything the corpus declares is re-exported from this module: the corpus has
//! no `package`, so it is one flat namespace, and pyatv's message and enum names are preserved
//! exactly (`SendCommandMessage`, `ProtocolMessage`, `ErrorCode`, …) with fields in Rust's snake
//! case as `prost` renders them.
//!
//! What `prost` does *not* generate is the proto2 extension machinery, which is how MRP carries
//! every concrete message inside the `ProtocolMessage` envelope. [`extensions`] fills that gap;
//! read its documentation before touching the message layer, and
//! `docs/research/mrp-protobuf-spike.md` for why it exists.

pub mod extensions;
pub mod wire;

/// Re-exported so callers can encode and decode the generated types without depending on `prost`
/// directly, and so a `prost` major bump is this crate's problem rather than every caller's.
pub use prost::Message;
pub use wire::{Field, Scanner, WireType};

/// Code generated by `prost-build`; see the module documentation.
///
/// Kept in its own module so the lint exemptions below cannot leak into hand-written code.
#[allow(
    clippy::pedantic,
    reason = "prost-build's output trips 194 pedantic lints on this corpus (116 doc_markdown, 74 \
              must_use_candidate, 4 too_many_lines); it is generated from pyatv's .proto files and \
              not ours to restyle. Deliberately narrower than `clippy::all`, which it does not \
              trip, so a real correctness lint on generated code would still be a build failure."
)]
mod generated {
    include!(concat!(env!("OUT_DIR"), "/mrp_protobuf.rs"));
}

pub use generated::*;
