//! Loader for `mrp_extension_kat.json`, the cross-implementation extension vectors.
//!
//! The file is generated by `gen_mrp_extension_kat.py` in this directory from pyatv and pyatv's
//! own protobuf runtime; see that script's header for how to regenerate it. It is embedded with
//! `include_str!` so the tests never touch the filesystem and a missing file is a compile error
//! rather than a skipped test.
//!
//! A vector that has silently changed shape must fail loudly, so every accessor panics with the
//! offending field name rather than quietly yielding `None`.

use serde_json::Value;

/// One serialised `ProtocolMessage` and everything known about its extension field.
///
/// Two integration tests include this module and each reads a different subset of the fields, so
/// dead-code analysis — which runs per test binary — flags whatever the other one uses.
#[derive(Debug)]
#[allow(
    dead_code,
    reason = "each test binary consumes a different subset of the vector"
)]
pub struct Vector {
    /// Vector name, used to select the typed assertions and in failure messages.
    pub name: String,
    /// Why the vector exists; carried through so a failure explains itself.
    pub note: String,
    /// `ProtocolMessage.Type` constant name, e.g. `"SEND_COMMAND_MESSAGE"`.
    pub type_name: String,
    /// `ProtocolMessage.Type` value.
    pub message_type: i32,
    /// Extension field name as declared in the `.proto`, or `None` for a bare envelope.
    pub extension_name: Option<String>,
    /// Extension field number, or `None` for a bare envelope.
    ///
    /// A handful of pyatv's factories — `get_keyboard_session()` and the `GENERIC_MESSAGE`
    /// heartbeat — send an envelope with no payload at all, so the vector has no extension to
    /// name.
    pub extension_number: Option<u32>,
    /// The `uniqueIdentifier` pyatv stamped on the envelope.
    pub unique_identifier: String,
    /// The whole serialised envelope, extension included.
    pub protocol_message: Vec<u8>,
    /// The extension payload on its own, for message-typed extensions.
    pub inner: Option<Vec<u8>>,
    /// The extension value, for the one string-typed extension.
    pub inner_string: Option<String>,
}

/// Parse the embedded vectors.
#[must_use]
pub fn load() -> Vec<Vector> {
    let document: Value = serde_json::from_str(include_str!("mrp_extension_kat.json"))
        .expect("mrp_extension_kat.json is not valid JSON; regenerate it");

    document
        .get("vectors")
        .and_then(Value::as_array)
        .expect("mrp_extension_kat.json has no `vectors` array")
        .iter()
        .map(parse)
        .collect()
}

/// Turn one JSON object into a [`Vector`].
fn parse(value: &Value) -> Vector {
    Vector {
        name: string(value, "name"),
        note: string(value, "note"),
        type_name: string(value, "type_name"),
        message_type: integer(value, "type"),
        extension_name: optional_string(value, "extension_name"),
        extension_number: optional_integer(value, "extension_number")
            .map(|number| u32::try_from(number).expect("extension_number out of range")),
        unique_identifier: string(value, "unique_identifier"),
        protocol_message: bytes(value, "protocol_message"),
        inner: optional_bytes(value, "inner"),
        inner_string: value
            .get("inner_string")
            .and_then(Value::as_str)
            .map(str::to_owned),
    }
}

/// The string at `field`.
fn string(value: &Value, field: &str) -> String {
    value
        .get(field)
        .and_then(Value::as_str)
        .unwrap_or_else(|| panic!("vector field `{field}` is missing or not a string"))
        .to_owned()
}

/// The string at `field`, or `None` when it is JSON null.
fn optional_string(value: &Value, field: &str) -> Option<String> {
    value.get(field)?.as_str().map(str::to_owned)
}

/// The integer at `field`, or `None` when it is JSON null.
fn optional_integer(value: &Value, field: &str) -> Option<i32> {
    let raw = value.get(field)?.as_i64()?;
    Some(
        i32::try_from(raw).unwrap_or_else(|_| panic!("vector field `{field}` does not fit in i32")),
    )
}

/// The integer at `field`.
fn integer(value: &Value, field: &str) -> i32 {
    let raw = value
        .get(field)
        .and_then(Value::as_i64)
        .unwrap_or_else(|| panic!("vector field `{field}` is missing or not an integer"));

    i32::try_from(raw).unwrap_or_else(|_| panic!("vector field `{field}` does not fit in i32"))
}

/// The hex string at `field`, decoded.
fn bytes(value: &Value, field: &str) -> Vec<u8> {
    optional_bytes(value, field)
        .unwrap_or_else(|| panic!("vector field `{field}` is missing or not a hex string"))
}

/// The hex string at `field`, decoded, or `None` when the field is JSON null.
fn optional_bytes(value: &Value, field: &str) -> Option<Vec<u8>> {
    let text = value.get(field)?.as_str()?;

    Some(
        hex::decode(text)
            .unwrap_or_else(|error| panic!("vector field `{field}` is not hex: {error}")),
    )
}
