//! Golden bytes: every outbound factory in [`pyatv_proto_mrp::messages`] must serialise to exactly
//! what pyatv's `pyatv/protocols/mrp/messages.py` produces for the same call.
//!
//! The reference bytes come from `tests/kat/mrp_extension_kat.json`, generated by running pyatv
//! itself with `uuid4()` patched to a fixed sequence (see `gen_mrp_extension_kat.py`). The only
//! non-deterministic field in an MRP message is `uniqueIdentifier`, so each test pins ours to the
//! value the vector recorded and then compares the whole serialised envelope byte for byte.
//!
//! This is the check that catches field-ordering, default-suppression and float-width mistakes
//! that a field-by-field assertion would wave through: proto2 lets an encoder omit a field that
//! equals its default, and a device that receives a `DeviceInfoMessage` with a field missing
//! rejects the connection.

mod kat;

use kat::Vector;
use pyatv_core::consts::{RepeatState, ShuffleState};
use pyatv_core::storage::InfoSettings;
use pyatv_proto_mrp::MrpMessage;
use pyatv_proto_mrp::messages::{self, OutputDeviceChange};
use pyatv_proto_mrp::protobuf::{Command, protocol_message::Type};

/// The pairing identifier `gen_mrp_extension_kat.py` pins (`PAIRING_ID` there).
const PAIRING_ID: &str = "89B3D2B7-9D62-4A5C-9E48-2C4F2A0B1D33";

/// Find the vector named `name`; a rename in the generator must fail, not silently skip.
fn vector(name: &str) -> Vector {
    kat::load()
        .into_iter()
        .find(|vector| vector.name == name)
        .unwrap_or_else(|| panic!("no vector named `{name}`"))
}

/// Assert that `message`, once its UUID is pinned, is byte-identical to the vector.
fn assert_matches(name: &str, mut message: MrpMessage) {
    let vector = vector(name);

    message
        .set_unique_identifier(vector.unique_identifier.clone())
        .expect("re-serialising with a pinned uniqueIdentifier");

    assert_eq!(
        message.message_type(),
        vector.message_type,
        "{name}: wrong ProtocolMessage.type ({})",
        vector.type_name
    );
    assert_eq!(
        hex::encode(message.bytes()),
        hex::encode(&vector.protocol_message),
        "{name}: bytes differ from pyatv's ({})",
        vector.note
    );
}

// --- The bring-up sequence -------------------------------------------------
//
// `MrpProtocol.start()` (`pyatv/protocols/mrp/protocol.py:150-170`): DEVICE_INFO, then
// pair-verify when credentials exist, then these three.

#[test]
fn device_information_matches_pyatv() {
    assert_matches(
        "device_info",
        messages::device_information(&InfoSettings::default(), PAIRING_ID, false)
            .expect("building DEVICE_INFO_MESSAGE"),
    );
}

#[test]
fn device_information_update_matches_pyatv() {
    assert_matches(
        "device_info_update",
        messages::device_information(&InfoSettings::default(), PAIRING_ID, true)
            .expect("building DEVICE_INFO_UPDATE_MESSAGE"),
    );
}

#[test]
fn set_connection_state_matches_pyatv() {
    assert_matches(
        "set_connection_state",
        messages::set_connection_state().expect("building SET_CONNECTION_STATE_MESSAGE"),
    );
}

#[test]
fn client_updates_config_matches_pyatv() {
    assert_matches(
        "client_updates_config",
        messages::client_updates_config().expect("building CLIENT_UPDATES_CONFIG_MESSAGE"),
    );
}

#[test]
fn get_keyboard_session_matches_pyatv() {
    assert_matches("get_keyboard_session", messages::get_keyboard_session());
}

#[test]
fn the_heartbeat_is_a_bare_generic_message() {
    assert_matches("generic_message", messages::create(Type::GenericMessage));
}

#[test]
fn wake_device_matches_pyatv() {
    assert_matches("wake_device", messages::wake_device());
}

// --- HID -------------------------------------------------------------------

#[test]
fn hid_select_press_matches_pyatv() {
    assert_matches(
        "send_hid_event_select_down",
        messages::send_hid_event(1, 0x89, true).expect("building SEND_HID_EVENT_MESSAGE"),
    );
}

#[test]
fn hid_select_release_matches_pyatv() {
    assert_matches(
        "send_hid_event_select_up",
        messages::send_hid_event(1, 0x89, false).expect("building SEND_HID_EVENT_MESSAGE"),
    );
}

/// `usagePage = 12` with `usage = 0xE9`: a two-byte usage that a big-endian slip would corrupt.
#[test]
fn hid_volume_up_press_matches_pyatv() {
    assert_matches(
        "send_hid_event_volume_up_down",
        messages::send_hid_event(12, 0xE9, true).expect("building SEND_HID_EVENT_MESSAGE"),
    );
}

// --- Commands --------------------------------------------------------------

#[test]
fn send_command_play_matches_pyatv() {
    assert_matches(
        "send_command_play",
        messages::command(Command::Play).expect("building SEND_COMMAND_MESSAGE"),
    );
}

#[test]
fn send_command_pause_matches_pyatv() {
    assert_matches(
        "send_command_pause",
        messages::command(Command::Pause).expect("building SEND_COMMAND_MESSAGE"),
    );
}

#[test]
fn send_command_next_matches_pyatv() {
    assert_matches(
        "send_command_next",
        messages::command(Command::NextTrack).expect("building SEND_COMMAND_MESSAGE"),
    );
}

/// pyatv assigns a Python `int` to the `double` field `skipInterval`; the wire form is a `double`.
#[test]
fn skip_forward_matches_pyatv() {
    assert_matches(
        "send_command_skip_forward",
        messages::skip_command(Command::SkipForward, messages::DEFAULT_SKIP_TIME)
            .expect("building SEND_COMMAND_MESSAGE"),
    );
}

#[test]
fn seek_to_position_matches_pyatv() {
    assert_matches(
        "send_command_seek",
        messages::seek_to_position(90.0).expect("building SEND_COMMAND_MESSAGE"),
    );
}

#[test]
fn repeat_all_matches_pyatv() {
    assert_matches(
        "repeat_all",
        messages::repeat(RepeatState::All).expect("building SEND_COMMAND_MESSAGE"),
    );
}

#[test]
fn shuffle_songs_matches_pyatv() {
    assert_matches(
        "shuffle_songs",
        messages::shuffle(ShuffleState::Songs).expect("building SEND_COMMAND_MESSAGE"),
    );
}

// --- Volume, artwork, output devices ---------------------------------------

#[test]
fn set_volume_matches_pyatv() {
    assert_matches(
        "set_volume",
        messages::set_volume("E510C430-B01D-45DF-B558-6EA6F8251069", 0.42)
            .expect("building SET_VOLUME_MESSAGE"),
    );
}

/// pyatv's defaults are `width=-1`, `height=400` (`messages.py:100-109`).
#[test]
fn playback_queue_request_matches_pyatv() {
    assert_matches(
        "playback_queue_request",
        messages::playback_queue_request(0, -1.0, 400.0)
            .expect("building PLAYBACK_QUEUE_REQUEST_MESSAGE"),
    );
}

#[test]
fn add_output_devices_matches_pyatv() {
    assert_matches(
        "add_output_devices",
        messages::modify_output_context(
            OutputDeviceChange::Add,
            &["DEVICE-A".to_owned(), "DEVICE-B".to_owned()],
        )
        .expect("building MODIFY_OUTPUT_CONTEXT_REQUEST_MESSAGE"),
    );
}

#[test]
fn remove_output_devices_matches_pyatv() {
    assert_matches(
        "remove_output_devices",
        messages::modify_output_context(OutputDeviceChange::Remove, &["DEVICE-A".to_owned()])
            .expect("building MODIFY_OUTPUT_CONTEXT_REQUEST_MESSAGE"),
    );
}

#[test]
fn set_output_devices_matches_pyatv() {
    assert_matches(
        "set_output_devices",
        messages::modify_output_context(OutputDeviceChange::Set, &["DEVICE-A".to_owned()])
            .expect("building MODIFY_OUTPUT_CONTEXT_REQUEST_MESSAGE"),
    );
}

// --- Pairing ---------------------------------------------------------------

/// `is_pairing` is `True` only for pair-setup M1; every other exchange passes `False`.
#[test]
fn crypto_pairing_matches_pyatv() {
    // HAP TLV8: Method(0x00) = 0x00, SeqNo(0x06) = 0x01.
    let tlv = [0x00, 0x01, 0x00, 0x06, 0x01, 0x01];
    assert_matches(
        "crypto_pairing",
        messages::crypto_pairing(&tlv, true).expect("building CRYPTO_PAIRING_MESSAGE"),
    );
}
